controller_manager:
  ros__parameters:
    update_rate: 100  # Lower rate for testing
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

diff_drive_controller:
  ros__parameters:
    use_sim_time: true
    
    left_wheel_names: ["back_left_wheel_joint" , "front_left_wheel_joint"]
    right_wheel_names: ["back_right_wheel_joint" , "front_right_wheel_joint"]
    
    wheel_separation: 0.45
    wheel_radius: 0.1
    
    use_stamped_vel: false 
    publish_rate: 50.0
    
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    
    enable_odom_tf: true
    
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
    
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0